# Generated by Django 5.0.6 on 2024-06-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="дата")),
            ],
            options={
                "verbose_name": "меню",
                "verbose_name_plural": "меню",
                "db_table": "menus",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "db_table": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "num_portions",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="количество порций"
                    ),
                ),
                (
                    "how_to",
                    models.TextField(
                        max_length=4096, null=True, verbose_name="инструкция"
                    ),
                ),
            ],
            options={
                "verbose_name": "блюдо",
                "verbose_name_plural": "блюда",
                "db_table": "recipes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuRecipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mealtime",
                    models.CharField(
                        choices=[
                            ("breakfast", "завтрак"),
                            ("lunch", "обед"),
                            ("dinner", "ужин"),
                        ],
                        max_length=16,
                    ),
                ),
                ("count", models.FloatField(default=1.0, verbose_name="количество")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakfast_recipes",
                        to="food.menu",
                        verbose_name="меню",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakfast_recipes",
                        to="food.recipe",
                        verbose_name="блюдо",
                    ),
                ),
            ],
            options={
                "verbose_name": "блюдо",
                "verbose_name_plural": "завтрак",
                "db_table": "menu_recipes",
                "ordering": ["recipe__name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(verbose_name="вес")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.product",
                        verbose_name="продукт",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="food.recipe",
                        verbose_name="блюдо",
                    ),
                ),
            ],
            options={
                "verbose_name": "ингредиент",
                "verbose_name_plural": "ингредиенты",
                "db_table": "ingredients",
                "ordering": ["-weight", "product__name"],
                "unique_together": {("recipe", "product")},
            },
        ),
    ]
