# Generated by Django 5.0.6 on 2024-06-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menurecipes",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_recipes",
                to="food.menu",
                verbose_name="меню",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="how_to",
            field=models.TextField(
                blank=True, max_length=4096, null=True, verbose_name="инструкция"
            ),
        ),
    ]
