# Generated by Django 5.0.6 on 2024-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_alter_menurecipes_menu_alter_recipe_how_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_in_grocery_list",
            field=models.BooleanField(
                default=True, verbose_name="показывать в списке покупок"
            ),
        ),
    ]
