# Generated by Django 5.0.6 on 2024-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0003_product_show_in_grocery_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="тег"),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="menurecipes",
            options={
                "ordering": ["recipe__name"],
                "verbose_name": "блюдо",
                "verbose_name_plural": "блюда",
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="food.tag"),
        ),
    ]
